HW Numpy


1. What is a Python library? Why do we use Python libraries?


A Python library is a collection of functions and methods that allows you to perform many actions without writing your own code. We use Python libraries to leverage existing implementations for various tasks, saving time and effort in development.

Q2. What is the difference between Numpy array and List?


The difference between a NumPy array and a list is that a NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. A list, on the other hand, can contain elements of different data types and is indexed by integers.

Q3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

Shape: (3, 4)
Size: 12
Dimension: 2

Q4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
#4
array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

first_row = array[0]
print(first_row)


[1, 2, 3, 4]


Q5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
#5
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

element = array[2, 3]
print(element)


12


Q6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
#6
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

odd_elements = array[:, 1::2]
print(odd_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


Q7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [13]:
#7
import numpy as np

random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.58067701 0.97041599 0.8602673 ]
 [0.94639607 0.81565042 0.51463843]
 [0.72568346 0.36239551 0.57097499]]


Q8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand generates random values from a uniform distribution over [0, 1) in a specified shape, while np.random.randn generates random values from a standard normal distribution with mean 0 and standard deviation 1.

Q9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [25]:
#9
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

expanded_array = np.expand_dims(array, axis=0)
print(expanded_array.shape)


(1, 3, 4)


Q10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [18]:
#10
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

transposed_array = np.transpose(array)
print(transposed_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Q11. Consider the following matrix:  
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]  
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]  
Perform the following operation using Python  
1 Index wise multiplication  
2 Matrix multiplication  
3 Add both the matrix  
4 Subtact matrix A- B    
5 Divide Matrix B by A   

In [30]:
#11
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

index_wise_multiplication = A * B
matrix_multiplication = np.dot(A, B.T)
addition = A + B
subtraction = A - B
division = B / A

print("Index-wise multiplication:", index_wise_multiplication)
print("Matrix multiplication:", matrix_multiplication)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Division:", division)

Index-wise multiplication: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication: [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Q12. Which function in Numpy can be used to swap the byte order of an array?


The function in NumPy that can be used to swap the byte order of an array is np.ndarray.byteswap().

In [1]:
import numpy as np

# Create an array with elements of different byte orders
arr = np.array([1, 256], dtype=np.int16)  # 1 is represented as 0x0001 in little-endian, and 256 as 0x0100

# Swap the byte order of the array
arr_swapped = arr.byteswap()

print("Original array:", arr)        # Output: [  1 256]
print("Swapped byte order:", arr_swapped)  # Output: [  256 1]


Original array: [  1 256]
Swapped byte order: [256   1]


Q13. What is the significance of the np.linalg.inv function?


The np.linalg.inv function calculates the multiplicative inverse of a matrix. It's significant in linear algebra for solving systems of linear equations and finding the determinant of a matrix.

Q14. What does the np.reshape function do, and how is it used?


The np.reshape function in NumPy is used to change the shape of an array without changing its data. It can be used to convert a 1D array into a multidimensional array or to change the shape of an existing multidimensional array. For example:

In [11]:
import numpy as np

arr = np.arange(1, 10) # Creates a 1D array from 1 to 9
reshaped_arr = np.reshape(arr, (3, 3)) # Reshapes the array to a 3x3 matrix
print(reshaped_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q15. What is broadcasting in Numpy?

Broadcasting in NumPy is a mechanism that allows arrays of different shapes to be used together in arithmetic operations. When operating on two arrays, NumPy compares their shapes element-wise. Two dimensions are compatible when they are equal, or one of them is 1. If these conditions are not met, NumPy throws a ValueError. Broadcasting enables efficient vectorized computations without the need for explicit loops.